### ISSUE TITLE
Port for Nintendo 3ds Systems ?

### ISSUE THREAD

**Issue by BertBR** [eezstreet/OpenD2#14]
Is there a way to port Diablo 2 to Nintendo 3ds systems ?

I think this game will run pretty good on 3ds/new 3ds hardware.

Here is a DevKit and libraries that would be useful:

https://www.3dbrew.org/wiki/Homebrew_Libraries_and_Tools

**Comment by Lectem** [comment]
I think we'll need to start by having something decent on PC (both windows and linux) before porting on 3ds :)

**Comment by cxong** [comment]
3DS display resolution is 400x240. It would be unreadable.

**Comment by jthack** [comment]
> I think we'll need to start by having something decent on PC (both windows and linux) before porting on 3ds :)

How's it progressing?

**Comment by BertBR** [comment]
> 3DS display resolution is 400x240. It would be unreadable.

I know, but New 3ds XL has the following spec's:

Nintendo 3DS XL - 4.88 inch display @ 800x240 = 171.15 or 95.59 PPI in 3D Mode

**Comment by Lectem** [comment]
3D mode means 400x240 per eye, not 800x240. The console is not powerful enough anyway.

**Comment by BertBR** [comment]
> 3D mode means 400x240 per eye, not 800x240. The console is not powerful enough anyway.

I meant, 3ds XL is higher than normal 3ds.  O think it's good enough to run a Diablo 2 port.

There's a HomeBrew Port of Diablo for NDS. So i think it should be possible to port Diablo 2 for 3ds.

**Comment by Lectem** [comment]
> I meant, 3ds XL is higher than normal 3ds

No. I've developed for 3ds, and this is not the case.
I think you mean the "horizontal anti-aliasing", but in the end the screens are 400x240 per eye.

See https://3dbrew.org/wiki/Hardware .

**Comment by BertBR** [comment]
> > I meant, 3ds XL is higher than normal 3ds
> 
> No. I've developed for 3ds, and this is not the case.
> I think you mean the "horizontal anti-aliasing", but in the end the screens are 400x240 per eye.
> 
> See https://3dbrew.org/wiki/Hardware .

So, this project won't be ported to 3DS....

Sadly, because it's a great game and 3DS users will love play it. :(
