### ISSUE TITLE
After compile with Linux? 

### ISSUE THREAD

**Issue by sosproduction** [eezstreet/OpenD2#20]
Hello All.  I have set up this amazing project on my ubuntu machine and after configuring all the SDL packages I have a good compile.  But when I compile... of course it says I need to specify a basepath.... my question is (and the project might not be this far along)...  but I am a bit confused about how to run the game.  

I have a purchased copy, and of course can download the client from Blizzard for Mac or Windows, but how does this help me with Ubuntu?   Do you have to get the files onto a windows/mac machine and then copy them over to a linux directory?  i.e. .mpq files and all the files from the install for things to work?

Thanks!

**Comment by Bigorneau** [comment]
It's explained in the README, you have to provide the path to the game install in the command line  `+basepath="..."`

**Comment by sosproduction** [comment]
You cannot install Diablo2 on Linux.  It's a windows/mac program.  Correct?  How do you set a basepath on Ubuntu to a codebase that is windows/mac only?

**Comment by Bigorneau** [comment]
You can use [Wine](https://appdb.winehq.org/objectManager.php?sClass=application&iId=74) or [Play On Linux](https://www.playonlinux.com/en/app-16-Diablo_II.html)

**Comment by sosproduction** [comment]
Excellent.  Yes, I thought that it would be a situation where I had to get the files into Linux in some manner. Much appreciated. :)
