### ISSUE TITLE
Read access violation error when initializing SDL rendering system

### ISSUE THREAD

**Issue by w1lford** [eezstreet/OpenD2#5]
The exception is thrown at line 1007 in Renderer_SDL.cpp,  in the build pallets for loop, saying pal was nullptr. Any idea what might be causing this issue? The only slightly unusual thing I've done to the code is run it with the -w argument.

**Comment by eezstreet** [comment]
It means it can't find the assets. You need to launch it with `+basepath="Your path to Diablo II folder here"` and run it.
