### ISSUE TITLE
OpenD2 error

### ISSUE THREAD

**Issue by russo-2025** [eezstreet/OpenD2#7]
Я попробовал запустить OpenD2.
вот что из этого вышло.

Translate google:
I tried to run an OpenD2.
that's what came of it.

![1](https://user-images.githubusercontent.com/28739948/38380977-0a25c962-390e-11e8-83cf-66a5a6046ec9.png)
![2](https://user-images.githubusercontent.com/28739948/38380984-0eec44ee-390e-11e8-9c85-24ddb68de9cb.png)

Log: [1 - D2180405.txt](https://github.com/eezstreet/OpenD2/files/1881032/1.-.D2180405.txt)
_________________________________________________________________________________________________________
Я заметил, что в ошибке нет файла «patchstring.tbl».
я добавил «expandstring.tbl» и «string.tbl» в Patch_D2.мпк.
Вот что было дальше.

Translate google:
I noticed that there is no "patchstring.tbl" file in the error.
I added "expandstring.tbl" and "string.tbl" in "Patch_D2.mpq".
This is what happened next.

![1](https://user-images.githubusercontent.com/28739948/38381431-6c7effd8-390f-11e8-8eb3-9d44bc0920ae.png)
![2](https://user-images.githubusercontent.com/28739948/38381436-7107841c-390f-11e8-9e8b-8c77fcd204ae.png)
![3](https://user-images.githubusercontent.com/28739948/38381442-735f69aa-390f-11e8-9a05-b299fe011548.png)

Log: [D2180405.txt](https://github.com/eezstreet/OpenD2/files/1881058/D2180405.txt)

**Comment by eezstreet** [comment]
Hi,

The lack of text on buttons might be because you are using the Russian version of the game. If you look here:
https://github.com/eezstreet/OpenD2/blob/master/Shared/D2Shared.hpp#L43-L44

These two lines determine the language that is used by the engine. I have not tested the game in other languages, primarily because I do not own a non-English copy of the game. However, if you are able to fix the game to work properly in another language, I will happily accept a Pull Request.

Thanks

**Comment by russo-2025** [comment]
к сожалению моих знаний для этого недостаточно, извините.
Translate google:
unfortunately my knowledge is not enough for this, sorry.

**Comment by russo-2025** [comment]
Это оригинальная Diablo 2 lod  (not OpenD2)
Translate google:
this is the original Diablo 2 lod  (not OpenD2)

![image 15](https://user-images.githubusercontent.com/28739948/38393662-2f6b7e76-3934-11e8-9513-040264e10110.png)

UPD: я переместил все файлы локализации(включая шрифты и пр) в "Patch_D2.mpq".
После чего все начало работать.Несмотря на это, русский язык по прежнему не отображается
Translate google:
I moved all the localization files (including fonts, etc.) to "Patch_D2.mpq".
After which everything began to work.Despite this, the Russian language is still not displayed.

![image 16](https://user-images.githubusercontent.com/28739948/38394515-7d93ec02-3937-11e8-8b1c-7f79691b2d08.png)
