### ISSUE TITLE
 Cyrillic fonts are not displayed

### ISSUE THREAD

**Issue by russo-2025** [eezstreet/OpenD2#8]
Мне кажется проблема с отображением шрифтов кириллицы(P.S. Это то же самое что и латиница для английского).
Поправив "TBL::Register", я добился нормального возврата функции, но по прежнему без результата.

It seems to me a problem with the display of Cyrillic fonts (P.S. This is the same as Latin for English).
Correcting "TBL :: Register", I achieved a normal return of the function, but still without result.

______________________________________________________________________________________________________________
![image 1](https://user-images.githubusercontent.com/28739948/38458987-cc8dcdac-3aac-11e8-9ae9-846743eeb40e.png)

______________________________________________________________________________________________________________
Вот две версии перевода, которые чаще всего используют.
Here are two versions of the translation that most often use.

[[Russian Localization].zip](https://github.com/eezstreet/OpenD2/files/1886650/Russian.Localization.zip)

______________________________________________________________________________________________________________
P.S. translate google

**Comment by russo-2025** [comment]
Мне кажется что есть определенные проблемы с чтением файлов из "mpq" (data/exp и т д).
Потому что после переноса файлов английской локализации в "Patch_D2.mpq" все заработало.
Возможно это из-за не оригинальных "mpq", к сожалению я не могу найти 100% оригинальных файлов.

It seems to me that there are certain problems with reading files from "mpq" (data / exp and so on).
Because after the transfer of the files of English localization in "Patch_D2.mpq" everything worked.
Maybe it's because of the non-original "mpq", unfortunately I can not find 100% original files.


______________________________________________________________________________________________________________
Мне понравился ваш проект, но я не могу вам помочь.Так как недавно начал изучать с++. 
Хочу у вас спросить, насколько у вас серьезные намерения его развивать? Извините за мой английский.

I liked your project, but I can not help you. Since I recently started studying with c++. I want to ask you, how serious are your intentions to develop it? Sorry for my English.

**Comment by eezstreet** [comment]
Hi,

I intend to develop this more fully, once I have time.
