### ISSUE TITLE
Issue regarding copyright...and "cease and desist" letters.

### ISSUE THREAD

**Issue by ghost** [eezstreet/OpenD2#9]
You might want to be careful with making a mod like this because it seems Blizzard makes "cease-and desist" letters all the time regarding these mods.

Source: https://www.vg247.com/2017/07/25/world-of-warcraft-legacy-server-shut-down-by-cease-and-desist-letter-just-5-hours-after-launch/

**Comment by eezstreet** [comment]
I've taken serious considerations about this when starting up the project, and I've decided on the following measures to be safe:

 * The cinematics won't work (it uses BINK video, which is proprietary. Reverse engineering it is not something I want to get my fingers into, legally)
 * Battle.net, both closed and open, won't work (I don't want to allow people to cheat on legitimate game channels owned by Blizzard)

**Comment by ghost** [comment]
**My Suggestion** (considering how "trigger-happy" Blizzard is with lawsuits, unlike other game companies):

- Produce your updates in bulk rather than individually, meaning that if your project here just cancelled, you're still going to have a functional open-source Diablo 2.

- Encourage people to download your software (as well as the source code if you can provide it) so that **IF** Blizzard sends a "cease-and-desist" letter, you can always let another developer take over.
